### ISSUE TITLE
use wrong price when increase position

### ISSUE THREAD

**Issue by h3xag0nx** [HMXOrg/v2-evm#343]
Per stated comment, this should be `!_vars.isLong`

https://github.com/HMXOrg/v2-evm/blob/5d58891c1db1dee0477bad5b7cf9cb17a072e580/src/services/TradeService.sol#L305

https://github.com/HMXOrg/v2-evm/blob/5d58891c1db1dee0477bad5b7cf9cb17a072e580/src/services/TradeService.sol#L314

**Comment by shutsuwei** [comment]
max and min price feature is deprecated and not active.
